-- 코드를 입력하세요
SELECT a.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) as SCORE
FROM REST_INFO as a
JOIN REST_REVIEW as b
ON a.REST_ID = b.REST_ID
GROUP BY b.REST_ID
HAVING a.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC