-- 코드를 입력하세요
SELECT TITLE, REPLY.BOARD_ID, REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS, DATE_FORMAT(REPLY.CREATED_DATE,'%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD as BOARD 
RIGHT JOIN USED_GOODS_REPLY as REPLY
ON BOARD.BOARD_ID = REPLY.BOARD_ID
WHERE DATE_FORMAT(BOARD.CREATED_DATE,'%Y-%m') ='2022-10'
ORDER BY CREATED_DATE,TITLE

