-- 코드를 입력하세요
SELECT a.CAR_ID,a.CAR_TYPE,ROUND(a.DAILY_FEE * 30 * (100 - b.DISCOUNT_RATE) / 100, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS a
JOIN (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
      WHERE DURATION_TYPE = '30일 이상') AS b      
ON a.CAR_TYPE = b.CAR_TYPE
WHERE a.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                      WHERE START_DATE < '2022-12-01' AND END_DATE >='2022-11-01')
GROUP BY a.CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC,CAR_TYPE,CAR_ID
                      